CREATE TABLE candidatos (
    id SERIAL PRIMARY KEY AUTO_INCREMENT,
    foto VARCHAR(255) NOT NULL,
    nome VARCHAR(100) NOT NULL,
    numero VARCHAR(5),
    partido VARCHAR(100),
    data_criacao TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    votos INT NOT NULL DEFAULT 0
); 